# Generated by Django 2.1.3 on 2018-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='local_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='regon',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.IntegerField(),
        ),
    ]
