# Generated by Django 2.1.3 on 2018-11-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20181123_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.Client'),
        ),
    ]
