# Generated by Django 2.1.3 on 2018-12-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20181129_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
