# Generated by Django 2.1.3 on 2018-12-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_brutto',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_netto',
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_percentage',
            field=models.FloatField(default=23, max_length=10),
        ),
    ]
