# Generated by Django 2.1.3 on 2019-01-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
