# Generated by Django 2.1.3 on 2019-01-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_user_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='category',
        ),
    ]
