# Generated by Django 2.1.3 on 2019-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_auto_20190118_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
